version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # Uncomment and adjust the following lines if you need to pass through a serial device for Arduino
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - ARDUINO_PORT=/dev/ttyACM0
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
